### PR TITLE
ported nakama-unreal to cocos2d-x

### PR DESCRIPTION
**Pull request by Dimon4eg**
cocos2d-x 3.16
Currently works on windows, mac and ios

### CODE REVIEW

**Comment by novabyte** [comment]
@Dimon4eg This is a monumental effort :godmode: Thanks so much for the work! 

Would you be prepared to license your contributions under Apache-2?

**Comment by Dimon4eg** [comment]
Sure, license under Apache-2.
It's power of open source! :+1:

**Comment by mofirouz** [comment]
Hey @Dimon4eg This is awesome. I'll merge it in this weekend - could you DM me over on Gitter? Thanks!

**Comment by Dimon4eg** [comment]
Should be easy to merge because your repo is empty 😉

**Pull request merged**
